### ISSUE TITLE
Broken link in HTML docs

### ISSUE THREAD

**Issue by jhenin** [GrossfieldLab/loos#1]
http://grossfieldlab.github.io/loos/_convergence.html

**Comment by agrossfield** [comment]
Interestingly, the bug only manifests on GitHub, not when it's run locally.  It looks like the issue occurs when links start with a capital letter (several other links are broken).  We should have a fix up later today.

**Comment by tromo** [comment]
The problem is a combination of doxygen prepending filenames with an underscore and GitHub's jekyll  treating those as special files.  This does not affect local copies of the docs nor the version on sourceforge.  I've turned off jekyll processing for the GitHub pages and have not noticed any side-effects.
