### ISSUE TITLE
Apparent incompatibility between AmberTools and LOOS from conda

### ISSUE THREAD

**Issue by lgsmith** [GrossfieldLab/loos#123]
## Describe the bug
Installing AmberTools and LOOS in the same conda env, both from conda-forge, now produces symbol lookup errors again.

## To Reproduce

```
mamba create -n testatl_coinstall -c conda-forge loos ambertools
```
Now, call any loos tool, or try to start a python interpreter and import it. You'll see an error like:
```
aligner: symbol lookup error: path/to/miniconda3/envs/testatl_coinstall/bin/../lib/libloos.so: undefined symbol: _ZN5gemmi3cif18read_mmjson_insituEPcmRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
## Expected behavior

I'd expect to have a normal functional install where when I call the tool I get the short help message.

## LOOS version and platform

Linux, fresh miniconda install, versions:
```
mamba --version
mamba 1.5.8
conda 24.7.1
python --version
Python 3.12.5
```
Based on looking it up in the conda env, boost-lib was 1.84, ambertools 23.6.

## Additional context

I noticed that the boost version started out as 1.86, and then when I installed ambertools it changed to 1.84. I wonder if loos is somehow not compiled versus that boost, but conda doesn't know it.

Due to this peculiarity, I also tried installing them sequentially, loos first, and saw that asking for ambertools changes the boost version that gets installed.

**Comment by agrossfield** [comment]
This looks like a mamba error to me. Boost is very finicky, and if you use their compiled tools, you can only be compatible with exactly 1 version of it. LOOS recently got auto-updated to build against the latest boost, and mamba handled the dependencies incorrectly. I’m willing to be that you can compile loos in that environment just fine.

More generally, I don’t think this is something we can fix: ensuring that every other package can also be installed in the same environment will be an insane amount of work (and likely impossible).

________________________________
Dr. Alan Grossfield
Dept of Biochemistry and Biophysics
University of Rochester Medical Center
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789
Pronouns: He/his



From: lgsmith ***@***.***>
Date: Tuesday, September 3, 2024 at 12:08 PM
To: GrossfieldLab/loos ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [GrossfieldLab/loos] Apparent incompatibility between AmberTools and LOOS from conda (Issue #123)
Describe the bug

Installing AmberTools and LOOS in the same conda env, both from conda-forge, now produces symbol lookup errors again.

To Reproduce

mamba create -n testatl_coinstall -c conda-forge loos ambertools

Now, call any loos tool, or try to start a python interpreter and import it. You'll see an error like:

aligner: symbol lookup error: path/to/miniconda3/envs/testatl_coinstall/bin/../lib/libloos.so: undefined symbol: _ZN5gemmi3cif18read_mmjson_insituEPcmRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Expected behavior

I'd expect to have a normal functional install where when I call the tool I get the short help message.

LOOS version and platform

Linux, fresh miniconda install, versions:

mamba --version

mamba 1.5.8

conda 24.7.1

python --version

Python 3.12.5

Based on looking it up in the conda env, boost-lib was 1.84, ambertools 23.6.

Additional context

I noticed that the boost version started out as 1.86, and then when I installed ambertools it changed to 1.84. I wonder if loos is somehow not compiled versus that boost, but conda doesn't know it.

Due to this peculiarity, I also tried installing them sequentially, loos first, and saw that asking for ambertools changes the boost version that gets installed.

**Comment by lgsmith** [comment]
I think there's something wrong with the config, because LOOS doesn't break other boost dependent tools, they break it. Also there was a period where there was no issue with building this type of environment. You noted that mamba handled the dependencies incorrectly. So can we get them to handle the dependencies correctly? What's wrong there?

Conda produces the same issue given the above test case, so I assume you don't think it's literally mamba vs conda.

**Comment by agrossfield** [comment]
This issue should be attached to loos-feedstock, since the issue is with the conda packaging, not with loos itself. I'm looking into it now, and I have an idea for how to fix it.

**Comment by agrossfield** [comment]
A brief update: I have good news and bad news. The good news is I think I've figured out how to make conda-forge build multiple variants for different versions of boost. The bad news is that doing so is triggering a bug in conda-build on mac where you can't specify variants for packages that have a "-" in their name. It works just fine on linux, but not Mac. I've opened a bug report on the conda-build github page.

**Comment by lgsmith** [comment]
That’s wild, but it seems eminently addressable by them so likely to get
action. Thanks for looking into this further.

**Comment by agrossfield** [comment]
I think this is fixed by https://github.com/conda-forge/loos-feedstock/pull/17
