### ISSUE TITLE
Problems running any of the rdf tools 

### ISSUE THREAD

**Issue by krb0073** [GrossfieldLab/loos#17]
Hi All, 
I have been trying to use the rdf , and xy_rdf tools in LOOS 3.0. but I have not be able to get program to read either the psf or the dcd  , I am not sure which the program is failing on ,
that I am loading.  My last attempt is below:
 

- xy_rdf  ../../8020_final.psf centered_production_eq5-5-2.dcd 'segname == "PR"' 'resname == "DTAP" && name == "N"' 0 40 40

- # xy_rdf '../../8020_final.psf' 'centered_production_eq5-5-2.dcd' 'segname == "PR"' 'resname == "DTAP && name == "N" ' '0' '40' '40' -  

- terminate called after throwing an instance of 'loos::FileOpenError'
  what():  Error while opening 
Aborted

I Have not been able to find my mistake. I have tried using several different psf and dcd files but I get the same error. Thanks for your time.
, Kyle

**Comment by agrossfield** [comment]
Hi Kyle,

The only thing that’s jumping out at me is the dash at the end of the line in the second example. 
Other than that, I’m stuck. FileOpenError generally means exactly what it says, that it couldn’t open the file, not that it couldn’t read it. That would imply it’s not there ( eg filename is wrong), or that permissions are messed up. Did you try running a different LOOS tool (eg trajinfo or something else trivial)? Or for that matter opening them in VMD? 

I’m sorry I’m not being more help, but that’s all I see right now. 

Alan

**Comment by krb0073** [comment]
Alan, 
I have been able to load the trajectory in vmd and use density-dist , recenter-trj , and dibmops with the same files.  I at a loss as to what the problem is. 
,Kyle

**Comment by agrossfield** [comment]
I’ve got to admit, I’m stumped — all of loos uses the same reading code. I have 3 things to try.
1) say “which xy_rdf” and “which density-dist”, to verify you’re getting the same LOOS distro for tools that work and tools that don’t, because I suppose this could happen with a broken distribution, eg after an upgrade.
2) rebuild LOOS from scratch: scons -c; scons -c config; scons
3) send me the psf and dcd files and let me try to figure it out.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Aug 10, 2019, at 4:16 PM, krb0073 <notifications@github.com<mailto:notifications@github.com>> wrote:


Alan,
I have been able to load the trajectory in vmd and use density-dist , recenter-trj , and dibmops with the same files. I at a loss as to what the problem is.
,Kyle

**Comment by krb0073** [comment]
Alan,
1. Which:
which rdf
/usr/local/src/loos-3.0.0/bin/rd
 which xy_rdf
/usr/local/src/loos-3.0.0/bin/xy_rdf
2. I will reinstall the program today
3. The files will be in a tar ball attached to this email which was sent as
a google drive link due to size
 Kyle_system_files.tar.gz
<https://drive.google.com/a/mix.wvu.edu/file/d/10FYjbmG61fcVZUwGt8qoE6KlHh-3eu7t/view?usp=drive_web>
, Kyle

**Comment by agrossfield** [comment]
Ok, so my guess that you were pulling in 2 different loos distributions was clearly wrong.

Let me know if rebuilding works.

I'll take a look at the files you sent and see if I can reproduce the problem.

Alan

**Comment by agrossfield** [comment]
Hi Kyle,

I can reproduce your problem, and it's not anything due to your files.  It's related to some new functionality I integrated that lets you reweight results -- for some reason, it's trying to instantiate it even though you didn't ask for it, and the file open error is occuring because it's trying to open a weights file that doesn't exist.  I haven't figured out exactly what's going wrong yet, but I hope to get it done today.

I'm sorry this has inconvenienced you.

Alan

**Comment by agrossfield** [comment]
Hi Kyle,

It's fixed -- I pushed the changes to master a minute ago.  If you either re-download or do a git pull, then rebuild, you should be good to go.

If you're curious, the bug was a stupid one. In handling the command line options for reweighting, I never explicitly set the boolean to turn it off.  On some systems, the bool was getting initialized as false, but that's not defined behavior for the compiler. Now, I've got code in there to explicitly set it false.

Alan
