### ISSUE TITLE
issues with cylindrical-density

### ISSUE THREAD

**Issue by VBurns** [GrossfieldLab/loos#20]
I've been trying to use cylindrical-density.py and i keep getting with error:

cylindrical-density.py foo.prmtop foo-centered.mdcrd 'name == "CA"' 'resname == "PC" || resname == "PA" || resname == "OL"' -25 25 50 10 30 20
#  /usr/local/bin/cylindrical-density.py foo.prmtop foo-centered.mdcrd name == "CA" resname == "PC" || resname == "PA" || resname == "OL" -25 25 50 10 30 20
Traceback (most recent call last):
  File "/usr/local/bin/cylindrical-density.py", line 106, in <module>
    hist[rbin, zbin] += 1.0
IndexError: index 50 is out of bounds for axis 1 with size 50

LOOS has been set up with python3, so i know it's not the python version. I don't know where the problem is.

**Comment by agrossfield** [comment]
I think I fixed it -- unlucky roundoff.  Can you check out the fix-cyl-density branch and see if it fixes it for you?

If you don't want to do that, you can edit cylindrical-density.py (or copy it and edit the new version), so that the offending line (line 106) is replaced by this:

`if (0 <= rbin < rnum_bins) and (0 <= zbin < znum_bins):
          hist[rbin, zbin] += 1.0`

Let me know, so I can merge and close the issue if this is it (or delve deeper if it isn't).

Alan

**Comment by VBurns** [comment]
It's works. Thank you so much Alan!

**Comment by agrossfield** [comment]
Awesome.  I’ll merge it tonight.

Alan

________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789


On Oct 24, 2019, at 4:41 PM, VBurns <notifications@github.com<mailto:notifications@github.com>> wrote:


It's works. Thank you so much Alan!

**Comment by agrossfield** [comment]
Fix is merged in
