### ISSUE TITLE
OMG TM-helix LOOS Secondary structure 

### ISSUE THREAD

**Issue by krb0073** [GrossfieldLab/loos#23]
Hi All , 
Recently I have been using the OMG to build oligomeric retinal proteins. After running the program the 3D structure of the changed. I was wondering if you all know what could have cause the change.

Before OMG 
![Befor_OMG](https://user-images.githubusercontent.com/41389987/72560414-04bc4d80-3875-11ea-99a2-25b3842e1921.png)
After OMG 
![After_OMG](https://user-images.githubusercontent.com/41389987/72560481-23224900-3875-11ea-9d00-e0313dc70c89.png)

Kyle

**Comment by agrossfield** [comment]
Hi Kyle,

That’s pretty surprising — all that happens during OMG is a bunch of short minimizations and dynamics runs.  The minimizations and dynamics are only 100 steps each, and there’s a restraint on the protein.  I suppose it’s possible that the protein could fall apart that fast, but I would think that would indicate something funky with the protein.  I have a couple of ideas:

Do a thorough restrained minimization of the protein before putting it into OMG.
Check to make sure the atom order in the pdb and psf match. Psfgen will change the order of the atoms relative to the original pdb file, so you need to write a pdb when you write the psf.  If you use the pdb you used to create the psf, it can do horrible things, because namd doesn’t check anything. 
Are the lipids packed well or badly around the protein? Does the system otherwise look sane? If so, it’s possible it’ll come back when you run it (though I’m not at all confident of this).

Let me know what happens. I don’t *think* there’s anything wrong with OMG, but obviously if I’m wrong I really want to know it.

Cheers,

Alan

________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789

**Comment by krb0073** [comment]
Alan,
Sorry this took so long but I finally was able to finish the list you gave me.

**Check to make sure the atom order in the pdb and psf match. Psfgen will change the order of the atoms relative to the original pdb file, so you need to write a pdb when you write the psf.**

The PSF and PDB for the system where made separating the parts of the system (water and ions , lipid plug in center , protein) into different structure files. The atom orders after PSFgen are the same in both files. All the waters place in the channels , the plugged lipids , and the retinal are all in the same PSF and PDB. My config for the OMG run is below. 
namd /usr/local/bin/namd2
psfgen /usr/local/bin/psfgen

topology /media/bak21/toppar/top_all36_prot.rtf
topology /media/bak21/toppar/top_all36_lipid.rtf
topology /media/bak11/toppar/top_all36_cgenff.rtf
#topology /media/bak21/toppar/top_all36_na.rtf
parameters /media/bak21/toppar/par_all36m_prot.prm
topology /media/bak21/toppar/toppar_water_ions_namd.str
topology /media/bak21/toppar/retinal-pro.str
#parameters /media/bak21/toppar/par_all32g2c_lipid-DTAPmodified-HK.inp
parameters /media/bak21/toppar/par_all36_lipid.prm
parameters /media/bak21/toppar/par_all36_carb.prm
parameters /media/bak21/toppar/par_all36_na.prm
parameters /media/bak21/toppar/par_all36_cgenff.prm
parameters /media/bak21/toppar/retinal-pro.str
parameters /media/bak21/toppar/toppar_water_ions_namd.str

protein MIN_EQ_OMG_KR2.pdb OMG_prp_6rew.psf  NONE 0

psf 6rew_bilayer.psf

box 200 200 150
 Upper leaflet
segment TPE POPE 225 19 P 1 /media/bak21/OPMLIB/lipid_library/pope_c36/
segment TPG POPG 75  19 P 1 /media/bak21/OPMLIB/lipid_library/popg_c36/
 Lower leaflet
segment BPE POPE 225 19 P -1 /media/bak21/OPMLIB/lipid_library/pope_c36/
segment BPG POPG 75  19 P -1 /media/bak21/OPMLIB/lipid_library/popg_c36/
 Salt and water. Note extra SOD to provide neutrality
water BULK TIP3 21000 50 14.7785 /usr/local/src/loos-3.0.0/OptimalMembraneGenerator/water_small.pdb
salt SOD SOD 214
salt CLA CLA 59

**Are the lipids packed well or badly around the protein?**

From just visual inspection the lipids around the protein seem to be okay . There are no lipids in that seem to be in weird confrontations or inside the helices.   

**Do a thorough restrained minimization of the protein before putting it into OMG.**

I ran minimization of 2,000 steps then 10 ps of dynamics in vacuum over the protein.  This was done ten times using the last runs position as the new staring structure

Here is the current protein backbone. 

![NEW_TRY_KR2](https://user-images.githubusercontent.com/41389987/75939833-5f2b6080-5e59-11ea-866c-7cba759023b8.png)

I'm at a loss to as to what could be off,
Kyle

**Comment by agrossfield** [comment]
Kyle, 

Is this still a live issue? If not, I'll close it. In any event, I'm sorry we weren't able to make things easier for you.

Alan
