### ISSUE TITLE
OMG/NAMD.py class not imposing constraints

### ISSUE THREAD

**Issue by krb0073** [GrossfieldLab/loos#31]
Hey All,
 I wanted to use the NAMD.py file that you have in the Optimal membrane Generator to make a restraint file but the output of the file is not looking any different that the starting PDB. 

Here is the file TEST.py that I am running this from:
##############################################
# Kyle 12/03/20
import loos 
import sys 
import loos.pyloos 
sys.path.append('/usr/local/src/loos-3.0.0/OptimalMembraneGenerator/')
from NAMD import NAMD 
PSF = sys.argv[1]
PDB = sys.argv[2]
box = loos.GCoord(377, 377, 1000)
system = loos.createSystem(PDB)
SYSTEM = NAMD(PSF,PDB,'test.pdb','PARM.inp', box ,None)
SYSTEM.write_restraintfile( './' ,system,spring=10)

#######################################

I have no clue what is giving me trouble with the NAMD.py code, but the *.con.pdb file has no changes from the *.pdb. I think the function NAMD.write_restraintfile was supposed to set Heavy atom positions == (10,0,0)  &&  non heavy postions == (0,0,0) ?Any thought on what I am doing wrong?
Kyle

**Comment by agrossfield** [comment]
I'm looking at the code, and that is what it's intended to do. I suspect there's a dumb bug, but I'll have to do some testing to be sure. For what it's worth, I don't think you did anything dumb.

**Comment by agrossfield** [comment]
Hi Kyle,

Ugh, this is what happens when you add in a piece of functionality but never use it.

I believe this is now fixed (see https://github.com/GrossfieldLab/loos/commit/cefe91df23962964b298669a3e41a7e4794ec1ff) for details.

Just FYI, with version 3.2 the import of individual modules within OMG has changed, which would break your example code. The import of NAMD will be:

`from loos.OptimalMembraneGenerator import NAMD`

and then you'd need to invoke the NAMD class as NAMD.NAMD

These days we recommend working with a conda install, and the manual path-wrangling you did shouldn't be necessary.

If the fix works for you, please let me know so I can close the issue. If it doesn't, obviously let me know also.

Cheers,

Alan

**Comment by krb0073** [comment]
Alan, 
I got it to work perfectly. Thanks for your help . While playing with the Namd.py,the directory variable seems not to matter in write_constraint . The function will always put the pdb in the location of the original pdb if the user provides the full path in the configuration file. It has no effect on the how the code runs. My fix was to do:
self.cons_k_filename = (self.start.pdb[:-4] + ".cons.pdb").split("/")[-1]

Kyle

**Comment by agrossfield** [comment]
Crap -- I should fix that too before I close the issue

**Comment by agrossfield** [comment]
The directory bug is fixed by

https://github.com/GrossfieldLab/loos/commit/b14b8eed8988a5b6c9f8c90bbd1dd070dbe12509
