### ISSUE TITLE
Trouble using subsetter with OpenMM trajectories

### ISSUE THREAD

**Issue by MehtapIsik** [GrossfieldLab/loos#40]
**Describe the bug**
I am having trouble using subsetter reimaging for OpenMM trajectories when I use OpenMM's PDB file for topology. For systems which were setup with OpenMM Modeller instead of Ambertools, I can only generate a PDB file for topology. Connectivity information is not correctly captured when I use OpenMM's PDB file for topology. What is the recommended way for using subsetter for OpenMM trajectories?

**To Reproduce**
This is the command I am trying to run:
`subsetter -C 'resname != "HOH" && resname != "CL" && resname!= "NA"' --reimage=aggressive -s 'resname != "HOH"  && resname != "CL" && resname!= "NA"' -i 10 traj_s10_reimaged equilibrated.pdb traj_short.dcd
`

This results in the following warning and disconnected atoms within molecules:
`WARNING- the model has no connectivity.  Assigning bonds based on distance.`

![image](https://user-images.githubusercontent.com/8997658/111639063-488c4900-87d1-11eb-82ed-5878fd3f9d69.png)
Three missing bonds are visible in this image on the RNA backbone.

Here is an example of my OpenMM trajectory files:
[openmm_outputs_for_loos_issue.zip](https://github.com/GrossfieldLab/loos/files/6164739/openmm_outputs_for_loos_issue.zip)

**LOOS version and platform**
I am using LOOS 3.3 on MacOS 10.15.7. I installed LOOS in a conda environment using the `conda_build.sh` script.

**Comment by agrossfield** [comment]
Hi,

Assigning bonds based on distance is an ugly hack we threw in, but it's not really reliable. It's trying to work around the fact that there's no bond information in the PDB (which would show up as CONECT records) -- this isn't surprising, since the standard only requires CONECT records for HETATMS).

I have 2 resulting questions: 

1. what are you trying to accomplish, precisely? If I recall correctly, the reimaging is the part that needs connectivity, and I'm not sure you'd actually need to do reimaging in this case (OpenMM keeps molecules in the same image, so you might just need to center the RNA). 
2. Is your system specified to OpenMM in their XML format? Supporting that directly has been on my TODO list for a while, and if I'm wrong and we can't find an easy workaround, then it's probably time for me to just implement it.

**Comment by MehtapIsik** [comment]
Hello,
I am surprised to have a response so quickly. Thank you.
1. In the full trajectory, I can see the molecule drifting between periodic boundaries. I don't think OpenMM keeps the molecules in the same image. I wish to reimage all the molecules back to the primary image.  I can still try centering. Which command would you recommend that I use for centering based on "A" residues?
2. Yes, I have the serialized OpenMM system saved as XML file. It can be a nice addition to support system XML files. 
[system.xml.zip](https://github.com/GrossfieldLab/loos/files/6165410/system.xml.zip)

**Comment by agrossfield** [comment]
Since the molecule remains intact -- as far as I know, gromacs is the only package that will split bonds across the periodic boundary -- there are 2-3 different tools that will do what you need:
- `recenter-trj` is a minimalist tool that reimages the trajectory such that the selected object stays at the origin.
- `aligner` is a bit more elaborate, in that it not only removes translation but also rotation. You can either align to a reference structure or do an iterative optimal alignment over the trajectory.
- `merge-traj` is optimal for a different use-case. If you've still got the trajectories running, it will merge them together by appending to an existing merged trajectory (e.g. so you can quickly add last night's data to an existing merged trajectory). It can also downsample the trajectory and center a particular selection in various ways (XY, Z, or whole box -- the last is what you'd want). I'll have to look, but `merge-traj` *might* require connectivity, I can't remember.

Thanks for the XML file. I can't promise I'll get it done immediately, but I'll move it up in priority.

Please let me know if you have trouble getting one of these tools to work for you.

**Comment by agrossfield** [comment]
Hi,

Am I crazy, or does the XML file not have any metadata -- atom name, residue name or number, etc -- in it? If so, I can still support it, but you won't like using it, because selections won't work (I can't select on residue names if I don't know them).

Alan

**Comment by agrossfield** [comment]
Another alternative solution: use parmed to read your xml file and have it spit back a file format that has bond info -- PSF and prmtop are both very rich formats that contain everything LOOS might try to use. Use that instead of the PDB file you wrote.

**Comment by MehtapIsik** [comment]
I am not very familiar with the contents of the system XML file. Thank you for your suggestions. I will try them and report back.

**Comment by agrossfield** [comment]
Sounds good. Assuming you find a good workaround (the more I think about it, the more I like the idea of using parmed to make something like a psf or prmtop), I'll want to write it up on the wiki as an example of how best to work with native OpenMM tools.

**Comment by agrossfield** [comment]
Hi Mehtap,

Can you let me know if you've got a good workaround? I'd like to close the issue, but I won't until I know you're happy.

Cheers,

Alan

**Comment by MehtapIsik** [comment]
Hello Alan,

Writing the PSF file from the OpenMM's Serialized System XML file with ParmEd is the approach that worked. Thank you for this suggestion! 

Here is how I generated the PSF file using XML and PDB files:

```
import parmed as pmd

struct = pmd.openmm.load_topology(pmd.load_file('../openmm_outputs/equilibrated.pdb').topology,
                               pmd.load_file('../openmm_outputs/system.xml'))
struct.save('system.psf', overwrite=True)
```

Best,
Mehtap

**Comment by agrossfield** [comment]
Awesome! Thanks for posting the solution -- that will help the next person who has a problem like this. I'll close this issue, and I'll add your code snippet to a page on working with LOOS and OpenMM.

Cheers,

Alan
