### ISSUE TITLE
Bonds for Martini protein residues not applying correctly

### ISSUE THREAD

**Issue by robincorey** [GrossfieldLab/loos#46]
Hi - I'm using LOOS gmxdump2pdb.pl to write Martini PDBs with CONECT records so that VMD can show bonds correctly. For lipids it works wonderfully, but for proteins it's only correctly assigning a subset of the residues. 

I've been using this command:
gmx dump -s md_1.tpr  | perl $GIT/loos/Tools/gmxdump2pdb.pl out

I've tried a number of different systems and sizes, in both Martini 2.2 and 3. I also tried including my top file in the gmx dump line but I always get the same result. Happy to share either tpr or output files.

In VMD I open either the PDB directly or the PSF then load the PDB into it.

If it's relevant, I'm getting these errors:

> Warning: Missing atom count in topology so inferring number of atoms in segment Protein at /sansom/s137/bioc1535/Desktop/git-repos/loos/Tools/gmxdump2pdb.pl line 594, <> line 151012.
> Warning: Missing atom count in topology so inferring number of atoms in segment CARD at /sansom/s137/bioc1535/Desktop/git-repos/loos/Tools/gmxdump2pdb.pl line 594, <> line 151012.
...
> Warning- Automatically mapping segment 'PROTEIN' to 'PRTN'

I'm using the current version of LOOS (git cloned on 10-May-2021), perl 5 version 26. Ubuntu 18.04.5.

Thanks

**Comment by agrossfield** [comment]
Can you attach the tpr file (or a minimal example that reproduces the problem)? Also, which version of gromacs are you using? The tpr file (and thus the output of gmx dump) is not compatible between versions, and sometimes stuff changes out from under us.

It's a longshot, but have you tried the --constraints or --vsites options? I don't recall proteins using them much, but it couldn't hurt to check.

@tromo : can you take a look when you have a chance?

Cheers,

Alan

**Comment by tromo** [comment]
Hi Robin, attaching an example tpr would be best.  This sounds like something is not being parsed correctly in the `gmx dump` output.

--Tod

**Comment by robincorey** [comment]
Hi both

Thanks very much for the replies. The --constraints option actually helps a lot, and the majority of residues are now correctly bonded. It's now just the first 100 beads or so that still have an issue.

I'm using gmx 2019.4 for both grompp and dump. I attach an example tpr, as well as the outputs I get when using --constraints.

Many thanks
Robin
[files.zip](https://github.com/GrossfieldLab/loos/files/6452670/files.zip)

**Comment by tromo** [comment]
Hi Robin, I _think_ the problem was some variation in the formatting of constraints.  I've pushed up a new version of `gmxdump2pdb.pl` that should account for that.  Please give this version a try (and still use `--constraints`) and let us know if this works.  FWIW, the warnings about inferring atom counts stem from an old change in the dump format and can be ignored.

**Comment by agrossfield** [comment]
Just to clarify what Tod wrote: you'll need to do the following:
```
git pull
scons PREFIX=$CONDA_PREFIX install  
```
The former pulls down the latest version of the code. The latter rebuilds and installs the code -- there should be nothing new to build, so all that will happen is it'll install the new version of gmxdump2pdb.pl

The next time you run
`gmx dump -s md_1.tpr | gmxdump2pdb.pl --constraints out`

it *ought* to work. I left out the path for gmxdump2pdb because it shouldn't be necessary if you did a conda install when you built. If you didn't build and install it, you'll need the commandline you used above, with the full path.

If perchance something else does go wrong, *PLEASE* let us know.

Cheers,

Alan

**Comment by robincorey** [comment]
Hi both

Thanks so much - yes, those changes worked perfectly and the script is now fully functional for my systems. I'll share the process with others in the Sansom and Stansfeld labs - I'm sure they'll be glad to know there's an easy way to get bonds showing in VMD.

Thanks for the quick replies and turnaround.  I'll have to check out the rest of LOOS when I get a chance.

Best 
Robin
