### ISSUE TITLE
PDB ensembles instead of repeated calls to `createSystem`

### ISSUE THREAD

**Issue by lgsmith** [GrossfieldLab/loos#82]
**Is your feature request related to a problem? Please describe.**
I'm dealing with large numbers of files that in LOOS's parlance are nominally models, but should actually be read by the same model file and just be used as different coordinates/conformations (I'm specifically dealing with PDBs, but I don't see why you wouldn't also want to be able to do this with other model-files that can contain coordinates). I would like to be able to write some kind of code that just reads new coordinates into a given AG from a collection of PDB files, rather than parsing each file as a new createSystem call. It's remarkable how much slower that parsing is when thosuands or tens of thousands of PDBs are involved.

Why not just use short (i.e. one frame) DCDs? Because I need the things to be PDBs for other scripts, so I'd have to write converters in a bunch of other places to flip back and forth between PDB and DCD, and that will be annoying. Also, with all that extra IO, it's not totally obvious that it will even be faster than just calling `createSystem` on each PDB independently.

**Describe the solution you'd like**
Two alternatives come to mind:
1. Some way to treat a list of file names as coordinates associated with a particular AG, like a multitrajectory or trajectory would where it's updating the subset of atoms associated with a selection each time I iterate through the list. Doesn't literally have to be a list. 
2. A method to an atomic group that goes something like `.getCoordsFrom('filename of eligible type')`

Critically, if the second solution is deemed to be better in subsequent discussion, the `getCoordsFrom` method should have an optional arg that gives you a way to provide a 'reading AG' so that you can update just a subset AG while still being able to parse the file, like what's done with trajectories (so you're not repeatedly calling `selectAtoms` on the 'reading AG' after each update).

It's occurred to me that if solution 2 is implemented in the correct way, it could also provide a quick framework for writing solution 1 and essentially providing a `PDBEnsemble` trajectory type. This could also give us a more graceful way to handle PDB trajectories/NMR ensembles, something that's been kind of missing (yes there are workarounds) for a while.

**Describe alternatives you've considered**
I'm not exactly sure how this could be implemented. Like I said, a workaround is to do everything with DCDs, but unfortunately most structural/comp-biology tools read pdb so it would be a nuisance to have tons of short DCDs floating around that are redundant to PDBs I have to write (and update) to match their contents.

**Additional context**
None, really, but happy to provide more details as needed.

**Comment by agrossfield** [comment]
I think the easiest way to do this is to read the first PDB as an `AtomicGroup` (using `loos.createSystem`), but read all of the others as `Trajectory` objects. LOOS already supports reading concatenated PDB files as `Trajectory` objects, so a single PDB file should work. You might get a slight performance win by concatenating them once and then reading the frame with `Trajectory.readFrame` or the pyloos equivalent, but I'd at least start by running `createTrajectory` (or the pyloos equivalent) each time to see if the overhead matters.

@tromo : going forward, do you think it would make sense to let createTrajectory read a glob of pdb files? I see a bunch of issues, so I think the answer is probably "no", but I wanted to throw it out there.

**Comment by tromo** [comment]
I think that should work.  Alternatively, use `pdbtraj` directly.  The latter requires the PDBs have a consistent naming scheme (e.g. `foo%05d.pdb`), but you can always use symlinks to get that.

The main issue here is that the typical pattern is to read a frame and operate on a subset.  When you use `createSystem()`, you are getting new `pAtoms`, so you have to run `selectAtoms()` again, which is more work than you should have to do.  Using a `Trajectory` will allow you to update a source model's atoms, as will `pdbtraj`.  I would wager that reading in a PDB with `CreateSystem()` and then using `copyCoordsFrom()` will be about as fast (this is what `pdbtraj` does behind the scenes).

Regarding changing `Trajectory`, I don't think it makes sense.  This is a specialization, so you'd want to use the appropriate trajectory class directly.  I think you could make the case for having `pdbtraj` accept a vector of filenames rather than a hard-coded scheme.

For that matter, if this is going to be in Python, then I'd make my own specialized trajectory class (in Python) that accepts a list of filenames (or glob), acts like a list, and behind the scenes does the above.  Most of the work (parsing, updating atoms) will be on the C++ side.
