### ISSUE TITLE
loos package is not available in conda-forge repository

### ISSUE THREAD

**Issue by RubenRam** [GrossfieldLab/loos#90]
**Describe the bug**
INSTALL file states the package is avaible in conda-forge when it is not.

**To Reproduce**
$ conda install -c conda-forge loos

**Expected behavior**
Installation of package and its dependencies

**LOOS version and platform**
Trying to install loos v4.0.0 in py3.7 with conda 22.9.0 on a  CentOS 7.9 with a fresh environment:

$ conda create --no-default-packages -n Loos_py3.7 python=3.7

**Additional context**
If the package is indeed not available in the conda-forge repository, please write a disclaimer in the INSTALL file, it is misleading.

**Comment by agrossfield** [comment]
I’m very sorry — we thought it would be done by now, and that’s why we didn’t actually announce the release. I suspect it will be accepted within the next day or two (we submitted the revised version of the recipe yesterday).

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Oct 27, 2022, at 4:10 AM, RubenRam ***@***.***> wrote:

﻿

Describe the bug
INSTALL file states the package is avaible in conda-forge when it is not.

To Reproduce
$ conda install -c conda-forge loos

Expected behavior
Installation of package and its dependencies

**LOOS version and platform
Trying to install loos v4.0.0 in py3.7 with conda 22.9.0 on a CentOS 7.9 with a fresh environment:

$ conda create --no-default-packages -n Loos_py3.7 python=3.7

Additional context
If the package is indeed not available in the conda-forge repository, please write a disclaimer in the INSTALL file, it is misleading.

**Comment by agrossfield** [comment]
Update: the feedstock pull request just got merged into main, so my guess is the package will appear in a few hours.

**Comment by agrossfield** [comment]
As of a few minutes ago, loos 4.0.1 is available for linux on conda-forge. Mac packages still have issues -- they show up, but they're broken. We're working on it and hope to have it fixed in the next couple of days.

**Comment by agrossfield** [comment]
Mac is available now too. The only think missing is the versions for python 3.11, which are still wending their way through the process.
